version: '3.8'

services:
  app:
    build: .
    container_name: my_app
    ports:
      - "8501:8501"  # Порт для Streamlit
    command: streamlit run scr/app.py --server.port=8501 --server.address=0.0.0.0

  test:
    build: .
    container_name: my_app_tests
    command: pytest tests/
