# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install DVC
      run: pip install dvc

    - name: Pull DVC data
      run: dvc pull
      env:
        DVC_REMOTE_USER: ${{ secrets.DVC_REMOTE_USER }}
        DVC_REMOTE_PASSWORD: ${{ secrets.DVC_REMOTE_PASSWORD }}

    - name: Build Docker image
      run: docker build -t my_app:latest .

    - name: Run tests
      run: docker run my_app:latest pytest tests

    - name: Run application
      run: docker run -d -p 8000:8000 my_app:latest

